### ISSUE TITLE
ValueError: masked arrays are not supported

### ISSUE THREAD

**Issue by ruifengma** [pykalman/pykalman#94]
there is a ValueError when I try to run the plot_em.py example. I use python 3.7 with numpy version 1.20.3 and scipy 1.6.3.

**Comment by mjroth** [comment]
It looks like an issue dealing with NaNs in `scipy` for `solve_triangular`. If you simply want to run the EM example without any calculation of the log-likelihoods, just comment out that calculation. i.e.
```
# Learn good values for parameters named in `em_vars` using the EM algorithm
loglikelihoods = np.zeros(10)
for i in range(len(loglikelihoods)):
    kf = kf.em(X=data.observations, n_iter=1)
    # loglikelihoods[i] = kf.loglikelihood(data.observations)
```
and comment out the final figure.

**Comment by mbalatsko** [comment]
Consider migration from pykalman to pykalman-bardo, as [pykalman](https://github.com/pykalman/pykalman) project is no longer maintained. There were some issues that were fixed, see: https://github.com/pybardo/pykalman/blob/v0.9.7/CHANGELOG

I'm going to maintain [pykalman-bardo](https://github.com/pybardo/pykalman), react to issues, and fix bugs. For now the API is the same as in the initial package, but it might evolve in time.

I hope you will find it useful for your project!

**Comment by sytham** [comment]
I still get this issue (also when switching to `pykalman-bardo`), when calling `filter_update`. Seems because in `filter_update` it always constructs a masked array, no way around it without modifying the code? From reading around on Scipy it seems there is also no scipy version that structurally supports masked arrays.

```
Python 3.9
pykalman-bardo-0.9.7
scipy 1.8.0
numpy 1.23.5
```
Stack trace
```
{
	"name": "ValueError",
	"message": "masked arrays are not supported",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [14], in <cell line: 4>()
      5 observation_covariance = obs_var_slope * filtered_state_mean ** 2
      6 transition_covariance = state_var_slope * filtered_state_mean ** 2
      8 filtered_state_mean, filtered_state_covariance =\\
----> 9     kf.filter_update(filtered_state_mean=filtered_state_mean,
     10                     filtered_state_covariance=filtered_state_covariance,
     11                     observation=xi,
     12                     observation_covariance=observation_covariance,
     13                     transition_covariance=transition_covariance
     14                  )
     15 mus[i] = filtered_state_mean
     16 sigmas[i] = np.sqrt(filtered_state_covariance)

File ~/workspace/py3.9_venv/lib/python3.9/site-packages/pykalman/standard.py:1281, in KalmanFilter.filter_update(self, filtered_state_mean, filtered_state_covariance, observation, transition_matrix, transition_offset, transition_covariance, observation_matrix, observation_offset, observation_covariance)
   1270     observation = np.ma.asarray(observation)
   1272 predicted_state_mean, predicted_state_covariance = (
   1273     _filter_predict(
   1274         transition_matrix, transition_covariance,
   (...)
   1277     )
   1278 )
   1279 (_, next_filtered_state_mean,
   1280  next_filtered_state_covariance) = (
-> 1281     _filter_correct(
   1282         observation_matrix, observation_covariance,
   1283         observation_offset, predicted_state_mean,
   1284         predicted_state_covariance, observation
   1285     )
   1286 )
   1288 return (next_filtered_state_mean, next_filtered_state_covariance)

File ~/workspace/py3.9_venv/lib/python3.9/site-packages/pykalman/standard.py:273, in _filter_correct(observation_matrix, observation_covariance, observation_offset, predicted_state_mean, predicted_state_covariance, observation)
    258 predicted_observation_mean = (
    259     np.dot(observation_matrix,
    260            predicted_state_mean)
    261     + observation_offset
    262 )
    263 predicted_observation_covariance = (
    264     np.dot(observation_matrix,
    265            np.dot(predicted_state_covariance,
    266                   observation_matrix.T))
    267     + observation_covariance
    268 )
    270 kalman_gain = (
    271     np.dot(predicted_state_covariance,
    272            np.dot(observation_matrix.T,
--> 273                   linalg.pinv(predicted_observation_covariance)))
    274 )
    276 corrected_state_mean = (
    277     predicted_state_mean
    278     + np.dot(kalman_gain, observation - predicted_observation_mean)
    279 )
    280 corrected_state_covariance = (
    281     predicted_state_covariance
    282     - np.dot(kalman_gain,
    283              np.dot(observation_matrix,
    284                     predicted_state_covariance))
    285 )

File ~/workspace/py3.9_venv/lib/python3.9/site-packages/scipy/linalg/_basic.py:1315, in pinv(a, atol, rtol, return_rank, check_finite, cond, rcond)
   1241 def pinv(a, atol=None, rtol=None, return_rank=False, check_finite=True,
   1242          cond=None, rcond=None):
   1243     \"\"\"
   1244     Compute the (Moore-Penrose) pseudo-inverse of a matrix.
   1245 
   (...)
   1313 
   1314     \"\"\"
-> 1315     a = _asarray_validated(a, check_finite=check_finite)
   1316     u, s, vh = _decomp_svd.svd(a, full_matrices=False, check_finite=False)
   1317     t = u.dtype.char.lower()

File ~/workspace/py3.9_venv/lib/python3.9/site-packages/scipy/_lib/_util.py:285, in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    283 if not mask_ok:
    284     if np.ma.isMaskedArray(a):
--> 285         raise ValueError('masked arrays are not supported')
    286 toarray = np.asarray_chkfinite if check_finite else np.asarray
    287 a = toarray(a)

ValueError: masked arrays are not supported"
}
```

**Comment by sytham** [comment]
> I still get this issue (also when switching to `pykalman-bardo`), when calling `filter_update`. Seems because in `filter_update` it always constructs a masked array, no way around it without modifying the code? From reading around on Scipy it seems there is also no scipy version that structurally supports masked arrays.

Solved this by replacing all `linalg.pinv` with `np.linalg.pinv` in `standard.py`

**Comment by fkiraly** [comment]
is this still a problem in the current `pykalman` dev branch after backmerge of the `sktime` fork?

If so, we should add the fix to the code base, and also a test for the failure.

PR would be much appreciated!

**Comment by DCchoudhury15** [comment]
Hi @fkiraly!
I've confirmed the bug exists with scipy 1.8.0 where scipy.linalg.pinv() throws ValueError: masked arrays are not supported.
Interestingly, scipy 1.17.0 (latest) doesn't have this issue - it handles masked arrays fine. However, since pykalman supports scipy<2.0.0, should i still apply the fix for backward compatibility?
I've replaced scipy.linalg.pinv with np.linalg.pinv (4 places) and added tests as requested. Works on both scipy versions.
Should I submit a PR?
